
apiVersion: v1
kind: ConfigMap

metadata:
  name: elasticsearch-config
  namespace: elasticsearch
  
  labels:
    app: elasticsearch
    component: configuration

data:
  elasticsearch.yml: |
    
   