apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  namespace: {{ .Values.namespace }}
  labels:
    app: elasticsearch
    managed-by: helm
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: elasticsearch
  ports:
    - name: transport
      port: {{ .Values.service.transportPort }}
      targetPort: 9300
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
  labels:
    app: elasticsearch
    managed-by: helm
spec:
  type: {{ .Values.service.type }}
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 9200
      protocol: TCP
