
apiVersion: v1
kind: ServiceAccount

metadata:
  name: elasticsearch
  namespace: elasticsearch
  
  labels:
    app: elasticsearch
    component: rbac


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: elasticsearch
  
  labels:
    app: elasticsearch
    component: rbac

rules:
  
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch", "list"]

 
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "watch", "list"]

  
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: elasticsearch
  
  labels:
    app: elasticsearch
    component: rbac

# Role reference: Which ClusterRole to use?
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticsearch

# Subjects: Who gets these permissions?
# Grant to: ServiceAccount "elasticsearch" in "elasticsearch" namespace
subjects:
  - kind: ServiceAccount
    name: elasticsearch
    namespace: elasticsearch
